# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: Test1234!
        POSTGRES_USER: hortus
    volumes:
      - "../data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
